endpoints: # the IP of the shards
  - "node-1:4000"
  - "node-2:4000"
  - "node-3:4000"
threads: 1 # number of threads that generate requests per shard
appends: 950 # appends per second for each thread
reads: 50 # reads per second for each thread
runtime: 40s # overall runtime
times: 10