// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.3
// source: shared_logpb/shared_log.proto

package shared_logpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record string `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Color  uint32 `protobuf:"varint,2,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_logpb_shared_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_logpb_shared_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_shared_logpb_shared_log_proto_rawDescGZIP(), []int{0}
}

func (x *AppendRequest) GetRecord() string {
	if x != nil {
		return x.Record
	}
	return ""
}

func (x *AppendRequest) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

type AppendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gsn uint64 `protobuf:"varint,1,opt,name=gsn,proto3" json:"gsn,omitempty"`
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_logpb_shared_log_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_logpb_shared_log_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_shared_logpb_shared_log_proto_rawDescGZIP(), []int{1}
}

func (x *AppendResponse) GetGsn() uint64 {
	if x != nil {
		return x.Gsn
	}
	return 0
}

type ReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gsn uint64 `protobuf:"varint,1,opt,name=gsn,proto3" json:"gsn,omitempty"`
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_logpb_shared_log_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_logpb_shared_log_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_shared_logpb_shared_log_proto_rawDescGZIP(), []int{2}
}

func (x *ReadRequest) GetGsn() uint64 {
	if x != nil {
		return x.Gsn
	}
	return 0
}

type ReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gsn    uint64 `protobuf:"varint,1,opt,name=gsn,proto3" json:"gsn,omitempty"`
	Record string `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_logpb_shared_log_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_logpb_shared_log_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_shared_logpb_shared_log_proto_rawDescGZIP(), []int{3}
}

func (x *ReadResponse) GetGsn() uint64 {
	if x != nil {
		return x.Gsn
	}
	return 0
}

func (x *ReadResponse) GetRecord() string {
	if x != nil {
		return x.Record
	}
	return ""
}

type TrimRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gsn uint64 `protobuf:"varint,1,opt,name=gsn,proto3" json:"gsn,omitempty"`
}

func (x *TrimRequest) Reset() {
	*x = TrimRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_logpb_shared_log_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrimRequest) ProtoMessage() {}

func (x *TrimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_logpb_shared_log_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrimRequest.ProtoReflect.Descriptor instead.
func (*TrimRequest) Descriptor() ([]byte, []int) {
	return file_shared_logpb_shared_log_proto_rawDescGZIP(), []int{4}
}

func (x *TrimRequest) GetGsn() uint64 {
	if x != nil {
		return x.Gsn
	}
	return 0
}

type TrimResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrimResponse) Reset() {
	*x = TrimResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_logpb_shared_log_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrimResponse) ProtoMessage() {}

func (x *TrimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_logpb_shared_log_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrimResponse.ProtoReflect.Descriptor instead.
func (*TrimResponse) Descriptor() ([]byte, []int) {
	return file_shared_logpb_shared_log_proto_rawDescGZIP(), []int{5}
}

var File_shared_logpb_shared_log_proto protoreflect.FileDescriptor

var file_shared_logpb_shared_log_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x6c, 0x6f, 0x67, 0x70, 0x62, 0x2f, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x6c, 0x6f, 0x67, 0x22, 0x3d, 0x0a, 0x0d, 0x41,
	0x70, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x22, 0x0a, 0x0e, 0x41, 0x70,
	0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x67, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x73, 0x6e, 0x22, 0x1f,
	0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x67, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x73, 0x6e, 0x22,
	0x38, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x67, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x73,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x1f, 0x0a, 0x0b, 0x54, 0x72, 0x69,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x73, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x73, 0x6e, 0x22, 0x0e, 0x0a, 0x0c, 0x54, 0x72,
	0x69, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc4, 0x01, 0x0a, 0x09, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x4c, 0x6f, 0x67, 0x12, 0x3f, 0x0a, 0x06, 0x41, 0x70, 0x70, 0x65,
	0x6e, 0x64, 0x12, 0x19, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x6c, 0x6f, 0x67, 0x2e,
	0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x41, 0x70, 0x70, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x04, 0x52, 0x65, 0x61,
	0x64, 0x12, 0x17, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x39, 0x0a, 0x04, 0x54, 0x72, 0x69, 0x6d, 0x12, 0x17,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x54, 0x72, 0x69, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x54, 0x72, 0x69, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6e, 0x61, 0x74, 0x68, 0x61, 0x6e, 0x69, 0x65, 0x6c, 0x74, 0x6f, 0x72, 0x6e, 0x6f, 0x77, 0x2f,
	0x50, 0x4d, 0x4c, 0x6f, 0x67, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x6c, 0x6f, 0x67,
	0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x6c, 0x6f, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_logpb_shared_log_proto_rawDescOnce sync.Once
	file_shared_logpb_shared_log_proto_rawDescData = file_shared_logpb_shared_log_proto_rawDesc
)

func file_shared_logpb_shared_log_proto_rawDescGZIP() []byte {
	file_shared_logpb_shared_log_proto_rawDescOnce.Do(func() {
		file_shared_logpb_shared_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_logpb_shared_log_proto_rawDescData)
	})
	return file_shared_logpb_shared_log_proto_rawDescData
}

var file_shared_logpb_shared_log_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shared_logpb_shared_log_proto_goTypes = []interface{}{
	(*AppendRequest)(nil),  // 0: shared_log.AppendRequest
	(*AppendResponse)(nil), // 1: shared_log.AppendResponse
	(*ReadRequest)(nil),    // 2: shared_log.ReadRequest
	(*ReadResponse)(nil),   // 3: shared_log.ReadResponse
	(*TrimRequest)(nil),    // 4: shared_log.TrimRequest
	(*TrimResponse)(nil),   // 5: shared_log.TrimResponse
}
var file_shared_logpb_shared_log_proto_depIdxs = []int32{
	0, // 0: shared_log.SharedLog.Append:input_type -> shared_log.AppendRequest
	2, // 1: shared_log.SharedLog.Read:input_type -> shared_log.ReadRequest
	4, // 2: shared_log.SharedLog.Trim:input_type -> shared_log.TrimRequest
	1, // 3: shared_log.SharedLog.Append:output_type -> shared_log.AppendResponse
	3, // 4: shared_log.SharedLog.Read:output_type -> shared_log.ReadResponse
	5, // 5: shared_log.SharedLog.Trim:output_type -> shared_log.TrimResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_logpb_shared_log_proto_init() }
func file_shared_logpb_shared_log_proto_init() {
	if File_shared_logpb_shared_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shared_logpb_shared_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_logpb_shared_log_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_logpb_shared_log_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_logpb_shared_log_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_logpb_shared_log_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrimRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_logpb_shared_log_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrimResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_logpb_shared_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_logpb_shared_log_proto_goTypes,
		DependencyIndexes: file_shared_logpb_shared_log_proto_depIdxs,
		MessageInfos:      file_shared_logpb_shared_log_proto_msgTypes,
	}.Build()
	File_shared_logpb_shared_log_proto = out.File
	file_shared_logpb_shared_log_proto_rawDesc = nil
	file_shared_logpb_shared_log_proto_goTypes = nil
	file_shared_logpb_shared_log_proto_depIdxs = nil
}
