// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.3
// source: sequencerpb/sequencer.proto

package sequencerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ORsp   *OrderResponse `protobuf:"bytes,1,opt,name=ORsp,proto3" json:"ORsp,omitempty"`
	Struct *Structure     `protobuf:"bytes,2,opt,name=Struct,proto3" json:"Struct,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sequencerpb_sequencer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_sequencerpb_sequencer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_sequencerpb_sequencer_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetORsp() *OrderResponse {
	if x != nil {
		return x.ORsp
	}
	return nil
}

func (x *Response) GetStruct() *Structure {
	if x != nil {
		return x.Struct
	}
	return nil
}

type OrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lsn          uint64 `protobuf:"varint,1,opt,name=Lsn,proto3" json:"Lsn,omitempty"`
	NumOfRecords uint32 `protobuf:"varint,2,opt,name=NumOfRecords,proto3" json:"NumOfRecords,omitempty"`
	Color        uint32 `protobuf:"varint,3,opt,name=Color,proto3" json:"Color,omitempty"`
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sequencerpb_sequencer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sequencerpb_sequencer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_sequencerpb_sequencer_proto_rawDescGZIP(), []int{1}
}

func (x *OrderRequest) GetLsn() uint64 {
	if x != nil {
		return x.Lsn
	}
	return 0
}

func (x *OrderRequest) GetNumOfRecords() uint32 {
	if x != nil {
		return x.NumOfRecords
	}
	return 0
}

func (x *OrderRequest) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

type OrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lsn          uint64 `protobuf:"varint,1,opt,name=Lsn,proto3" json:"Lsn,omitempty"`
	Gsn          uint64 `protobuf:"varint,2,opt,name=Gsn,proto3" json:"Gsn,omitempty"`
	NumOfRecords uint32 `protobuf:"varint,3,opt,name=NumOfRecords,proto3" json:"NumOfRecords,omitempty"`
	Color        uint32 `protobuf:"varint,4,opt,name=Color,proto3" json:"Color,omitempty"`
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sequencerpb_sequencer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sequencerpb_sequencer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_sequencerpb_sequencer_proto_rawDescGZIP(), []int{2}
}

func (x *OrderResponse) GetLsn() uint64 {
	if x != nil {
		return x.Lsn
	}
	return 0
}

func (x *OrderResponse) GetGsn() uint64 {
	if x != nil {
		return x.Gsn
	}
	return 0
}

func (x *OrderResponse) GetNumOfRecords() uint32 {
	if x != nil {
		return x.NumOfRecords
	}
	return 0
}

func (x *OrderResponse) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

type NodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IP string `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sequencerpb_sequencer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sequencerpb_sequencer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_sequencerpb_sequencer_proto_rawDescGZIP(), []int{3}
}

func (x *NodeInfo) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *NodeInfo) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

type Structure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch    uint32      `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Peers    []*NodeInfo `protobuf:"bytes,2,rep,name=Peers,proto3" json:"Peers,omitempty"`
	Adopters []*NodeInfo `protobuf:"bytes,3,rep,name=Adopters,proto3" json:"Adopters,omitempty"`
}

func (x *Structure) Reset() {
	*x = Structure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sequencerpb_sequencer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Structure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Structure) ProtoMessage() {}

func (x *Structure) ProtoReflect() protoreflect.Message {
	mi := &file_sequencerpb_sequencer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Structure.ProtoReflect.Descriptor instead.
func (*Structure) Descriptor() ([]byte, []int) {
	return file_sequencerpb_sequencer_proto_rawDescGZIP(), []int{4}
}

func (x *Structure) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Structure) GetPeers() []*NodeInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *Structure) GetAdopters() []*NodeInfo {
	if x != nil {
		return x.Adopters
	}
	return nil
}

var File_sequencerpb_sequencer_proto protoreflect.FileDescriptor

var file_sequencerpb_sequencer_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x70, 0x62, 0x2f, 0x73, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x22, 0x66, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x4f, 0x52, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x4f, 0x52,
	0x73, 0x70, 0x12, 0x2c, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x06, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x22, 0x5a, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x4c, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x4c,
	0x73, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x4e, 0x75, 0x6d, 0x4f, 0x66, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x4e, 0x75, 0x6d, 0x4f, 0x66, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x6d, 0x0a, 0x0d,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x4c, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x4c, 0x73, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x47, 0x73, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x47, 0x73,
	0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x4e, 0x75, 0x6d, 0x4f, 0x66, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x4e, 0x75, 0x6d, 0x4f, 0x66, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x2a, 0x0a, 0x08, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x22, 0x7d, 0x0a, 0x09, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x29, 0x0a, 0x05, 0x50, 0x65,
	0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x50, 0x65, 0x65, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x08, 0x41, 0x64, 0x6f, 0x70, 0x74, 0x65, 0x72,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x41, 0x64,
	0x6f, 0x70, 0x74, 0x65, 0x72, 0x73, 0x32, 0x49, 0x0a, 0x09, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x17, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6e, 0x61, 0x74, 0x68, 0x61, 0x6e, 0x69, 0x65, 0x6c, 0x74, 0x6f, 0x72, 0x6e, 0x6f, 0x77, 0x2f,
	0x50, 0x4d, 0x4c, 0x6f, 0x67, 0x2f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x2f,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_sequencerpb_sequencer_proto_rawDescOnce sync.Once
	file_sequencerpb_sequencer_proto_rawDescData = file_sequencerpb_sequencer_proto_rawDesc
)

func file_sequencerpb_sequencer_proto_rawDescGZIP() []byte {
	file_sequencerpb_sequencer_proto_rawDescOnce.Do(func() {
		file_sequencerpb_sequencer_proto_rawDescData = protoimpl.X.CompressGZIP(file_sequencerpb_sequencer_proto_rawDescData)
	})
	return file_sequencerpb_sequencer_proto_rawDescData
}

var file_sequencerpb_sequencer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sequencerpb_sequencer_proto_goTypes = []interface{}{
	(*Response)(nil),      // 0: sequencer.Response
	(*OrderRequest)(nil),  // 1: sequencer.OrderRequest
	(*OrderResponse)(nil), // 2: sequencer.OrderResponse
	(*NodeInfo)(nil),      // 3: sequencer.NodeInfo
	(*Structure)(nil),     // 4: sequencer.Structure
}
var file_sequencerpb_sequencer_proto_depIdxs = []int32{
	2, // 0: sequencer.Response.ORsp:type_name -> sequencer.OrderResponse
	4, // 1: sequencer.Response.Struct:type_name -> sequencer.Structure
	3, // 2: sequencer.Structure.Peers:type_name -> sequencer.NodeInfo
	3, // 3: sequencer.Structure.Adopters:type_name -> sequencer.NodeInfo
	1, // 4: sequencer.Sequencer.GetOrder:input_type -> sequencer.OrderRequest
	0, // 5: sequencer.Sequencer.GetOrder:output_type -> sequencer.Response
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sequencerpb_sequencer_proto_init() }
func file_sequencerpb_sequencer_proto_init() {
	if File_sequencerpb_sequencer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sequencerpb_sequencer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sequencerpb_sequencer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sequencerpb_sequencer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sequencerpb_sequencer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sequencerpb_sequencer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Structure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sequencerpb_sequencer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sequencerpb_sequencer_proto_goTypes,
		DependencyIndexes: file_sequencerpb_sequencer_proto_depIdxs,
		MessageInfos:      file_sequencerpb_sequencer_proto_msgTypes,
	}.Build()
	File_sequencerpb_sequencer_proto = out.File
	file_sequencerpb_sequencer_proto_rawDesc = nil
	file_sequencerpb_sequencer_proto_goTypes = nil
	file_sequencerpb_sequencer_proto_depIdxs = nil
}
