// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.3
// source: pedigreepb/pedigree.proto

package pedigreepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID    uint32           `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Structure *StructureUpdate `protobuf:"bytes,2,opt,name=structure,proto3" json:"structure,omitempty"`
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pedigreepb_pedigree_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pedigreepb_pedigree_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pedigreepb_pedigree_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterResponse) GetNodeID() uint32 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *RegisterResponse) GetStructure() *StructureUpdate {
	if x != nil {
		return x.Structure
	}
	return nil
}

type StructureUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch    uint32      `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Peers    []*NodeInfo `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	Adopters []*NodeInfo `protobuf:"bytes,3,rep,name=adopters,proto3" json:"adopters,omitempty"`
}

func (x *StructureUpdate) Reset() {
	*x = StructureUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pedigreepb_pedigree_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StructureUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructureUpdate) ProtoMessage() {}

func (x *StructureUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pedigreepb_pedigree_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructureUpdate.ProtoReflect.Descriptor instead.
func (*StructureUpdate) Descriptor() ([]byte, []int) {
	return file_pedigreepb_pedigree_proto_rawDescGZIP(), []int{1}
}

func (x *StructureUpdate) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *StructureUpdate) GetPeers() []*NodeInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *StructureUpdate) GetAdopters() []*NodeInfo {
	if x != nil {
		return x.Adopters
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IP string `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pedigreepb_pedigree_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pedigreepb_pedigree_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_pedigreepb_pedigree_proto_rawDescGZIP(), []int{2}
}

func (x *NodeInfo) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *NodeInfo) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pedigreepb_pedigree_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pedigreepb_pedigree_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pedigreepb_pedigree_proto_rawDescGZIP(), []int{3}
}

var File_pedigreepb_pedigree_proto protoreflect.FileDescriptor

var file_pedigreepb_pedigree_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x65, 0x64, 0x69, 0x67, 0x72, 0x65, 0x65, 0x70, 0x62, 0x2f, 0x70, 0x65, 0x64,
	0x69, 0x67, 0x72, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x22, 0x64, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65,
	0x49, 0x44, 0x12, 0x38, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x72, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x09, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x22, 0x83, 0x01, 0x0a,
	0x0f, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x29, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x72, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x70, 0x65, 0x65, 0x72,
	0x73, 0x12, 0x2f, 0x0a, 0x08, 0x61, 0x64, 0x6f, 0x70, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x61, 0x64, 0x6f, 0x70, 0x74, 0x65,
	0x72, 0x73, 0x22, 0x2a, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x44, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x81, 0x01, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x3c, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x73,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x1a, 0x1b, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b,
	0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x10, 0x2e, 0x73, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x30, 0x01, 0x42, 0x36, 0x5a, 0x34, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x74, 0x68, 0x61, 0x6e,
	0x69, 0x65, 0x6c, 0x74, 0x6f, 0x72, 0x6e, 0x6f, 0x77, 0x2f, 0x50, 0x4d, 0x4c, 0x6f, 0x67, 0x2f,
	0x70, 0x65, 0x64, 0x69, 0x67, 0x72, 0x65, 0x65, 0x2f, 0x70, 0x65, 0x64, 0x69, 0x67, 0x72, 0x65,
	0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pedigreepb_pedigree_proto_rawDescOnce sync.Once
	file_pedigreepb_pedigree_proto_rawDescData = file_pedigreepb_pedigree_proto_rawDesc
)

func file_pedigreepb_pedigree_proto_rawDescGZIP() []byte {
	file_pedigreepb_pedigree_proto_rawDescOnce.Do(func() {
		file_pedigreepb_pedigree_proto_rawDescData = protoimpl.X.CompressGZIP(file_pedigreepb_pedigree_proto_rawDescData)
	})
	return file_pedigreepb_pedigree_proto_rawDescData
}

var file_pedigreepb_pedigree_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pedigreepb_pedigree_proto_goTypes = []interface{}{
	(*RegisterResponse)(nil), // 0: sequencer.RegisterResponse
	(*StructureUpdate)(nil),  // 1: sequencer.StructureUpdate
	(*NodeInfo)(nil),         // 2: sequencer.NodeInfo
	(*Empty)(nil),            // 3: sequencer.Empty
}
var file_pedigreepb_pedigree_proto_depIdxs = []int32{
	1, // 0: sequencer.RegisterResponse.structure:type_name -> sequencer.StructureUpdate
	2, // 1: sequencer.StructureUpdate.peers:type_name -> sequencer.NodeInfo
	2, // 2: sequencer.StructureUpdate.adopters:type_name -> sequencer.NodeInfo
	2, // 3: sequencer.Node.Register:input_type -> sequencer.NodeInfo
	3, // 4: sequencer.Node.Heartbeat:input_type -> sequencer.Empty
	0, // 5: sequencer.Node.Register:output_type -> sequencer.RegisterResponse
	1, // 6: sequencer.Node.Heartbeat:output_type -> sequencer.StructureUpdate
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pedigreepb_pedigree_proto_init() }
func file_pedigreepb_pedigree_proto_init() {
	if File_pedigreepb_pedigree_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pedigreepb_pedigree_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pedigreepb_pedigree_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StructureUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pedigreepb_pedigree_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pedigreepb_pedigree_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pedigreepb_pedigree_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pedigreepb_pedigree_proto_goTypes,
		DependencyIndexes: file_pedigreepb_pedigree_proto_depIdxs,
		MessageInfos:      file_pedigreepb_pedigree_proto_msgTypes,
	}.Build()
	File_pedigreepb_pedigree_proto = out.File
	file_pedigreepb_pedigree_proto_rawDesc = nil
	file_pedigreepb_pedigree_proto_goTypes = nil
	file_pedigreepb_pedigree_proto_depIdxs = nil
}
