// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package shardpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShardClient is the client API for Shard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShardClient interface {
	Replicate(ctx context.Context, opts ...grpc.CallOption) (Shard_ReplicateClient, error)
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*OrderResponse, error)
}

type shardClient struct {
	cc grpc.ClientConnInterface
}

func NewShardClient(cc grpc.ClientConnInterface) ShardClient {
	return &shardClient{cc}
}

func (c *shardClient) Replicate(ctx context.Context, opts ...grpc.CallOption) (Shard_ReplicateClient, error) {
	stream, err := c.cc.NewStream(ctx, &Shard_ServiceDesc.Streams[0], "/sequencer.Shard/Replicate", opts...)
	if err != nil {
		return nil, err
	}
	x := &shardReplicateClient{stream}
	return x, nil
}

type Shard_ReplicateClient interface {
	Send(*ReplicationRequest) error
	Recv() (*OrderResponse, error)
	grpc.ClientStream
}

type shardReplicateClient struct {
	grpc.ClientStream
}

func (x *shardReplicateClient) Send(m *ReplicationRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *shardReplicateClient) Recv() (*OrderResponse, error) {
	m := new(OrderResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *shardClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/sequencer.Shard/Append", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShardServer is the server API for Shard service.
// All implementations must embed UnimplementedShardServer
// for forward compatibility
type ShardServer interface {
	Replicate(Shard_ReplicateServer) error
	Append(context.Context, *AppendRequest) (*OrderResponse, error)
	mustEmbedUnimplementedShardServer()
}

// UnimplementedShardServer must be embedded to have forward compatible implementations.
type UnimplementedShardServer struct {
}

func (UnimplementedShardServer) Replicate(Shard_ReplicateServer) error {
	return status.Errorf(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedShardServer) Append(context.Context, *AppendRequest) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedShardServer) mustEmbedUnimplementedShardServer() {}

// UnsafeShardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShardServer will
// result in compilation errors.
type UnsafeShardServer interface {
	mustEmbedUnimplementedShardServer()
}

func RegisterShardServer(s grpc.ServiceRegistrar, srv ShardServer) {
	s.RegisterService(&Shard_ServiceDesc, srv)
}

func _Shard_Replicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShardServer).Replicate(&shardReplicateServer{stream})
}

type Shard_ReplicateServer interface {
	Send(*OrderResponse) error
	Recv() (*ReplicationRequest, error)
	grpc.ServerStream
}

type shardReplicateServer struct {
	grpc.ServerStream
}

func (x *shardReplicateServer) Send(m *OrderResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *shardReplicateServer) Recv() (*ReplicationRequest, error) {
	m := new(ReplicationRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Shard_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sequencer.Shard/Append",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Shard_ServiceDesc is the grpc.ServiceDesc for Shard service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Shard_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sequencer.Shard",
	HandlerType: (*ShardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _Shard_Append_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Replicate",
			Handler:       _Shard_Replicate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "shardpb/shard.proto",
}
