// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.3
// source: shardpb/shard.proto

package shardpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record string `protobuf:"bytes,1,opt,name=Record,proto3" json:"Record,omitempty"`
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardpb_shard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shardpb_shard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_shardpb_shard_proto_rawDescGZIP(), []int{0}
}

func (x *AppendRequest) GetRecord() string {
	if x != nil {
		return x.Record
	}
	return ""
}

type ReplicationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lsn    uint64 `protobuf:"varint,1,opt,name=Lsn,proto3" json:"Lsn,omitempty"`
	Record string `protobuf:"bytes,2,opt,name=Record,proto3" json:"Record,omitempty"`
}

func (x *ReplicationRequest) Reset() {
	*x = ReplicationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardpb_shard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationRequest) ProtoMessage() {}

func (x *ReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shardpb_shard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationRequest.ProtoReflect.Descriptor instead.
func (*ReplicationRequest) Descriptor() ([]byte, []int) {
	return file_shardpb_shard_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicationRequest) GetLsn() uint64 {
	if x != nil {
		return x.Lsn
	}
	return 0
}

func (x *ReplicationRequest) GetRecord() string {
	if x != nil {
		return x.Record
	}
	return ""
}

type OrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lsn          uint64 `protobuf:"varint,1,opt,name=Lsn,proto3" json:"Lsn,omitempty"`
	Gsn          uint64 `protobuf:"varint,2,opt,name=Gsn,proto3" json:"Gsn,omitempty"`
	NumOfRecords uint32 `protobuf:"varint,3,opt,name=NumOfRecords,proto3" json:"NumOfRecords,omitempty"`
	Color        uint32 `protobuf:"varint,4,opt,name=Color,proto3" json:"Color,omitempty"`
	OriginColor  uint32 `protobuf:"varint,5,opt,name=OriginColor,proto3" json:"OriginColor,omitempty"`
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardpb_shard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shardpb_shard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_shardpb_shard_proto_rawDescGZIP(), []int{2}
}

func (x *OrderResponse) GetLsn() uint64 {
	if x != nil {
		return x.Lsn
	}
	return 0
}

func (x *OrderResponse) GetGsn() uint64 {
	if x != nil {
		return x.Gsn
	}
	return 0
}

func (x *OrderResponse) GetNumOfRecords() uint32 {
	if x != nil {
		return x.NumOfRecords
	}
	return 0
}

func (x *OrderResponse) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *OrderResponse) GetOriginColor() uint32 {
	if x != nil {
		return x.OriginColor
	}
	return 0
}

var File_shardpb_shard_proto protoreflect.FileDescriptor

var file_shardpb_shard_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x68, 0x61, 0x72, 0x64, 0x70, 0x62, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72,
	0x22, 0x27, 0x0a, 0x0d, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x3e, 0x0a, 0x12, 0x52, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x4c, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x4c, 0x73,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x8f, 0x01, 0x0a, 0x0d, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4c,
	0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x4c, 0x73, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x47, 0x73, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x47, 0x73, 0x6e, 0x12,
	0x22, 0x0a, 0x0c, 0x4e, 0x75, 0x6d, 0x4f, 0x66, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x4e, 0x75, 0x6d, 0x4f, 0x66, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x32, 0x8f, 0x01, 0x0a, 0x05,
	0x53, 0x68, 0x61, 0x72, 0x64, 0x12, 0x48, 0x0a, 0x09, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x12, 0x1d, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12,
	0x3c, 0x0a, 0x06, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x12, 0x18, 0x2e, 0x73, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x30, 0x5a,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x74, 0x68,
	0x61, 0x6e, 0x69, 0x65, 0x6c, 0x74, 0x6f, 0x72, 0x6e, 0x6f, 0x77, 0x2f, 0x50, 0x4d, 0x4c, 0x6f,
	0x67, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shardpb_shard_proto_rawDescOnce sync.Once
	file_shardpb_shard_proto_rawDescData = file_shardpb_shard_proto_rawDesc
)

func file_shardpb_shard_proto_rawDescGZIP() []byte {
	file_shardpb_shard_proto_rawDescOnce.Do(func() {
		file_shardpb_shard_proto_rawDescData = protoimpl.X.CompressGZIP(file_shardpb_shard_proto_rawDescData)
	})
	return file_shardpb_shard_proto_rawDescData
}

var file_shardpb_shard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shardpb_shard_proto_goTypes = []interface{}{
	(*AppendRequest)(nil),      // 0: sequencer.AppendRequest
	(*ReplicationRequest)(nil), // 1: sequencer.ReplicationRequest
	(*OrderResponse)(nil),      // 2: sequencer.OrderResponse
}
var file_shardpb_shard_proto_depIdxs = []int32{
	1, // 0: sequencer.Shard.Replicate:input_type -> sequencer.ReplicationRequest
	0, // 1: sequencer.Shard.Append:input_type -> sequencer.AppendRequest
	2, // 2: sequencer.Shard.Replicate:output_type -> sequencer.OrderResponse
	2, // 3: sequencer.Shard.Append:output_type -> sequencer.OrderResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shardpb_shard_proto_init() }
func file_shardpb_shard_proto_init() {
	if File_shardpb_shard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shardpb_shard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardpb_shard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardpb_shard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shardpb_shard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shardpb_shard_proto_goTypes,
		DependencyIndexes: file_shardpb_shard_proto_depIdxs,
		MessageInfos:      file_shardpb_shard_proto_msgTypes,
	}.Build()
	File_shardpb_shard_proto = out.File
	file_shardpb_shard_proto_rawDesc = nil
	file_shardpb_shard_proto_goTypes = nil
	file_shardpb_shard_proto_depIdxs = nil
}
